<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <logoVersion>1</logoVersion>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Conga CLM Suite - The Conga CLM Suite gives you complete visibility and control of your contract process. Easy to deploy and use, you gain benefits immediately – process control, risk management and high, immediate ROI.</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Conga CLM (Lightning)</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>INTL_Opportunity_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>International Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Security User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Billing</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Chatter External User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Chatter Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Chatter Moderator User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>System Administrator - Developer</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>StandardAul</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Solution Specialist</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Solution Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>SolutionManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>SalesforceIQ Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Salesforce API Only System Integrations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Sales Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Sales Manager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Sales Insights Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Sales Executive</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Read Only - Teladoc</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Product Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Product</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Minimum Access - Salesforce</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Minimum Access - API Only Integrations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Minimum Access - API Only Integrations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Marketo Sync</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>MarketingProfile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Marketing Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Marketing Executive</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Lead Development</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>IT / System Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>International Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Integration-Marketo</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Integration</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Identity User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Guest License User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Finance</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Executive Sponsor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>End User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Data Steward</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>CPQ Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>ContractManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Contract / Legal</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Client Support</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Employer_Service_Agreement_Self_Service_PDF</recordType>
        <type>Flexipage</type>
        <profile>Client Success</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Security User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Billing</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Chatter External User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Chatter Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Chatter Moderator User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>System Administrator - Developer</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>StandardAul</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Solution Specialist</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Solution Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>SolutionManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>SalesforceIQ Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Salesforce API Only System Integrations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Sales Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Sales Manager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Sales Insights Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Sales Executive</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Read Only - Teladoc</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Product Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Product</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Minimum Access - Salesforce</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Minimum Access - API Only Integrations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Minimum Access - API Only Integrations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Marketo Sync</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>MarketingProfile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Marketing Ops</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Marketing Executive</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Lead Development</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>IT / System Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>International Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Integration-Marketo</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Integration</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Identity User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Guest License User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Finance</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Executive Sponsor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>End User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Data Steward</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>CPQ Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>ContractManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Contract / Legal</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Client Support</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Agreement_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Apttus__APTS_Agreement__c</pageOrSobjectType>
        <recordType>Apttus__APTS_Agreement__c.Health_Plan_Services_Agreement</recordType>
        <type>Flexipage</type>
        <profile>Client Success</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>Apttus__APTS_Agreement__c</tabs>
    <tabs>Apttus__APTS_Template__c</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>Apttus__CycleTimeGroup__c</tabs>
    <tabs>Apttus__Document_Output_Formats</tabs>
    <tabs>Apttus__RetentionPolicy__c</tabs>
    <tabs>Apttus__Purge_Agreements</tabs>
    <tabs>Apttus__Obligation__c</tabs>
    <uiType>Lightning</uiType>
</CustomApplication>
